[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.virtualenv']

[phases.install]
cmds = [
  'python -m venv /app/venv',
  '/app/venv/bin/pip install --upgrade pip',
  '/app/venv/bin/pip install -r requirements.txt'
]

[phases.start]
cmd = '/app/venv/bin/python app.py'